apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: guestbook-ui-gateway
  namespace: prod
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http2
      protocol: HTTP2
    hosts:
      - "*"
