apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: guestbook-ui-gateway
  namespace: prod
spec:
  selector:
    app: guestbook-ui-prod-rollout
  servers:
  - port:
      number: 9080
      name: http2
      protocol: HTTP2
    hosts:
      - "*"
