apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - namespace.yaml
namespace: prod
labels:
  - includeSelectors: true
    pairs:
      env: prod
patches:
  - path: deployment.yaml
images:
  - newTag: "0.1"