apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rollout.yaml
  - virtualService.yaml
  - service.yaml
  - destinationRule.yaml
namespace: prod
labels:
  - includeSelectors: true
    pairs:
      env: prod
images:
  - name: gcr.io/heptio-images/ks-guestbook-demo
    newTag: "0.2"