apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - namespace.yaml
namespace: prod
labels:
  - includeSelectors: true
    pairs:
      env: prod
patches:
  - path: deployment.yaml
  - path: service.yaml
  - path: virtualService.yaml
images:
  - name: gcr.io/heptio-images/ks-guestbook-demo
    newTag: "0.1"