apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook-ui-prod-rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook-ui-prod-rollout
  template:
    metadata:
      labels:
        app: guestbook-ui-prod-rollout
        env: prod
    spec:
      containers:
      - name: guestbook-ui
        image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        ports:
        - containerPort: 80
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      canaryService: guestbook-ui-canary  # required
      stableService: guestbook-ui-primary  # required
      trafficRouting:
        istio:
          virtualService:
            name: guestbook-ui   # required
            routes:
            - primary
      steps:
      - setWeight: 25
      - pause:
          duration: 1m