apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-primary
spec:
  ports:
  - port: 9081
    targetPort: 80
  selector:
    app: guestbook-ui-prod-rollout
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-canary
spec:
  ports:
  - port: 9081
    targetPort: 80
  selector:
    app: guestbook-ui-prod-rollout