apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - namespace.yaml
namespace: dev
labels:
  - includeSelectors: true
    pairs:
      env: dev
patches:
  - path: deployment.yaml
images:
  - name: gcr.io/heptio-images/ks-guestbook-demo 
    newTag: "0.2"