apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - namespace.yaml
namespace: dev
labels:
  - includeSelectors: true
    pairs:
      env: dev
patches:
  - path: deployment.yaml
images:
  - newTag: "0.2"